name: 'A Basic App Github Action'
description: 'Does everything to get a container to my prod environment'
inputs:
  
  service: 
    description: 'the logical name for the service'
    required: true

  container: 
    description: 'the Docker image we are meant to pull and deploy'
    required: true

  exposed: 
    description: 'whether or not to setup a static IP'
    required: true
    default: true

  gke-cluster: 
    description: 'the name of the GKE cluster to which to deploy'
    required: true

  gke-project: 
    description: 'the project of the GKE cluster to which to deploy'
    required: true

  gke-zone: 
    description: 'the GKE zone to which to deploy'
    required: true

  gke-service-account-key:
    description: 'the GKE service account with which to deploy the application'
    required: true

  kubernetes-namespace:
    description: 'the Kubernetes namespace in which to deploy'
    required: true
    default: 'default'
  
  kubernetes-environment:
    description: 'Comma-separated list of environment variable keys to map'
    required: true

runs:
  using: 'composite'
  steps:

    # - name: Create Secrets object
    #   shell: bash
    #   env:
    #     ENV_KEYS: ${{ inputs.kubernetes-environment }}



    - name: Use Secrets object
      shell: bash
      run: |
        echo "Secrets: ${{ env.secrets }}"

    - name: "Setup PATH"
      shell: bash
      run: |
        P="${GITHUB_WORKSPACE}/bin"
        mkdir -p $P
        echo "${P}" >> $GITHUB_PATH

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ inputs.gke-service-account-key }}'

    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: '${{ inputs.gke-cluster  }}'
        location: '${{ inputs.gke-zone }}'

    - name: Set up Carvel Tools
      shell: bash
      run: |
        curl -L https://carvel.dev/install.sh | bash
        export PATH="$PATH:/usr/local/bin"
        ytt version

    - name: Deploy
      shell: bash
      env:
        ENV_KEYS: ${{ inputs.kubernetes-environment }}
      run: |
        gcloud config set project  ${{ inputs.gke-project }}
        gcloud --quiet auth configure-docker
        gcloud auth configure-docker us-docker.pkg.dev --quiet
        kubectl get ns/${{ inputs.kubernetes-namespace }} || kubectl create ns ${{ inputs.kubernetes-namespace }}
        kubectl config set-context --current --namespace=${{ inputs.kubernetes-namespace }}
        
        kubectl get pods

        cd $GITHUB_WORKSPACE
        export ROOT_DIR=$GITHUB_WORKSPACE
        export NAMESPACE_NAME=${{ inputs.kubernetes-namespace }}
        export APP_NAME=${{ inputs.service }}
        ls -la $GITHUB_WORKSPACE
        ls -la ${{ github.action_path }}
        ${{ github.action_path }}/bin/deploy.sh
